{
 "title": "BIG-IQ Telemetry",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(bigip_tmos_telemetry,hostname)"
    }
   },
   {
    "name": "stat",
    "label": "Metrics",
    "query": {
     "query": "label_values(bigip_tmos_telemetry{hostname=\"$hostname\"},stat)"
    }
   },
   {
    "name": "timerange",
    "label": "Statistics time range",
    "query": {
     "query": "label_values(bigip_tmos_telemetry{hostname=\"$hostname\",stat=\"$stat\"},timespan)"
    }
   },
   {
    "name": "tmos_cve",
    "label": "CVE",
    "query": {
     "query": "label_values(bigip_tmos_cve_details{hostname=\"$hostname\"},tmos_cve)"
    }
   },
   {
    "name": "severity",
    "label": "CVE severity",
    "query": {
     "query": "label_values(bigip_tmos_cve_details{hostname=\"$hostname\"},severity)"
    }
   },
   {
    "name": "base_score",
    "label": "CVE base score",
    "query": {
     "query": "label_values(bigip_tmos_cve_details{hostname=\"$hostname\"},base_score)"
    }
   },
   {
    "name": "exploitability_score",
    "label": "CVE exploitability score",
    "query": {
     "query": "label_values(bigip_tmos_cve_details{hostname=\"$hostname\"},exploitability_score)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BIG-IQ Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total BIG-IP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bigip_online_instances{job=\"f5tt\"}"
      }
     ]
    },
    {
     "title": "Hardware totals",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bigip_hwtotals{job=\"f5tt\"}",
       "legendFormat": "{{bigip_sku}}"
      }
     ]
    },
    {
     "title": "Software totals",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bigip_swtotals{job=\"f5tt\"}",
       "legendFormat": "{{bigip_module}}"
      }
     ]
    },
    {
     "title": "TMOS releases",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bigip_tmos_releases{job=\"f5tt\"}",
       "legendFormat": "{{tmos_release}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CVE Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CVE found",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count (bigip_tmos_cve_details)" }
     ]
    },
    {
     "title": "CVE by Severity - Summary",
     "type": "stat",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (bigip_tmos_cve_details)",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "CVE Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bigip_tmos_cve{job=\"f5tt\"}",
       "legendFormat": "{{tmos_cve}}"
      }
     ]
    },
    {
     "title": "CVE by Base Score - Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (base_score) (bigip_tmos_cve_details)",
       "legendFormat": "Base score {{base_score}}"
      }
     ]
    },
    {
     "title": "CVE by Exploitability Score - Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (exploitability_score) (bigip_tmos_cve_details)",
       "legendFormat": "Expl. Score {{exploitability_score}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CVE details for $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CVE found for $hostname",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (bigip_tmos_cve_details{hostname=~\"$hostname\",tmos_cve=~\"$tmos_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})"
      }
     ]
    },
    {
     "title": "CVE by Severity for $hostname",
     "type": "stat",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (bigip_tmos_cve_details{hostname=~\"$hostname\",tmos_cve=~\"$tmos_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "CVE summary for $hostname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (tmos_cve) (bigip_tmos_cve_details{hostname=~\"$hostname\",tmos_cve=~\"$tmos_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "CVE by Base Score for $hostname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (base_score) (bigip_tmos_cve_details{hostname=~\"$hostname\",tmos_cve=~\"$tmos_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
       "legendFormat": "Base score {{base_score}}"
      }
     ]
    },
    {
     "title": "CVE by Exploitability Score for $hostname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (exploitability_score) (bigip_tmos_cve_details{hostname=~\"$hostname\",tmos_cve=~\"$tmos_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
       "legendFormat": "Expl. Score {{exploitability_score}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System statitics for $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM usage - $hostname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"free-ram\",job=\"f5tt\"}",
       "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
      }
     ]
    },
    {
     "title": "CPU usage - $hostname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"cpu-usage\",job=\"f5tt\"}",
       "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
      }
     ]
    },
    {
     "title": "Available disk - $hostname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"disk-available-size\",job=\"f5tt\"}",
       "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic statistics for $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Client Traffic - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"client-bytes-in\",job=\"f5tt\"}",
     "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
    },
    {
     "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"client-bytes-out\",job=\"f5tt\"}",
     "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
    }
   ]
  },
  {
   "title": "Server Traffic - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"server-bytes-in\",job=\"f5tt\"}",
     "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
    },
    {
     "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"server-bytes-out\",job=\"f5tt\"}",
     "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
    }
   ]
  },
  {
   "title": "Server Connections - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bigip_tmos_telemetry{hostname=\"$hostname\",timespan=\"$timerange\",stat=\"server-connections\",job=\"f5tt\"}",
     "legendFormat": "{{hostname}} {{stat}} {{timerange}}"
    }
   ]
  }
 ]
}