{
 "title": "NGINX Instances",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(nginx_instances_online,subscription)"
    }
   },
   {
    "name": "instanceType",
    "label": "Instance Type",
    "query": {
     "query": "label_values(nginx_instances_online{subscription=\"$subscription\"},instanceType)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(nginx_cve_details,hostname)"
    }
   },
   {
    "name": "nginx_version",
    "label": "NGINX version",
    "query": {
     "query": "label_values(nginx_releases,release)"
    }
   },
   {
    "name": "nginx_cve",
    "label": "CVE",
    "query": {
     "query": "label_values(nginx_cve_totals,cve)"
    }
   },
   {
    "name": "severity",
    "label": "CVE severity",
    "query": {
     "query": "label_values(nginx_cve_details,severity)"
    }
   },
   {
    "name": "base_score",
    "label": "CVE base score",
    "query": {
     "query": "label_values(nginx_cve_details,base_score)"
    }
   },
   {
    "name": "exploitability_score",
    "label": "CVE exploitability score",
    "query": {
     "query": "label_values(nginx_cve_details,exploitability_score)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Subscription details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subscription",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1>$subscription</h1></center>"
   }
  },
  {
   "title": "Type",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "options": {
    "content": "<center><h1>$instanceType</h1></center>"
   }
  },
  {
   "title": "NGINX Usage Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 }, "options": { "content": "# NGINX Plus" } },
    { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 }, "options": { "content": "# NGINX OSS" } },
    {
     "title": "NGINX Plus",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_instances_online{type=\"nginx_plus\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "nginx_instances_offline{type=\"nginx_plus\"}",
       "legendFormat": "Offline"
      }
     ]
    },
    {
     "title": "NGINX Plus",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 2, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nginx_instances_online{type=\"nginx_plus\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "nginx_instances_offline{type=\"nginx_plus\"}",
       "legendFormat": "Offline"
      }
     ]
    },
    {
     "title": "NGINX OSS",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_instances_online{type=\"nginx_oss\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "nginx_instances_offline{type=\"nginx_oss\"}",
       "legendFormat": "Offline"
      }
     ]
    },
    {
     "title": "NGINX OSS",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nginx_instances_online{type=\"nginx_oss\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "nginx_instances_offline{type=\"nginx_oss\"}",
       "legendFormat": "Offline"
      }
     ]
    }
   ]
  },
  {
   "title": "CVE Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CVE found",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(nginx_cve_details)" }
     ]
    },
    {
     "title": "CVE by Severity - Summary",
     "type": "stat",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (nginx_cve_details)",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "CVE Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_cve_totals{job=\"f5tt\"}",
       "legendFormat": "{{cve}}"
      }
     ]
    },
    {
     "title": "CVE by Base Score - Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (base_score) (nginx_cve_details)",
       "legendFormat": "Base score {{base_score}}"
      }
     ]
    },
    {
     "title": "CVE by Exploitability Score - Summary",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (exploitability_score) (nginx_cve_details)",
       "legendFormat": "Expl. Score {{exploitability_score}}"
      }
     ]
    }
   ]
  },
  { "title": "CVE details for $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CVE found for $hostname",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (nginx_cve_details{hostname=~\"$hostname\",cve=~\"$nginx_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})"
    }
   ]
  },
  {
   "title": "CVE by Severity for $hostname",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity) (nginx_cve_details{hostname=~\"$hostname\",cve=~\"$nginx_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "CVE summary for $hostname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (cve) (nginx_cve_details{hostname=~\"$hostname\",cve=~\"$nginx_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "CVE by Base Score for $hostname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (base_score) (nginx_cve_details{hostname=~\"$hostname\",cve=~\"$nginx_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
     "legendFormat": "Base score {{base_score}}"
    }
   ]
  },
  {
   "title": "CVE by Exploitability Score for $hostname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (exploitability_score) (nginx_cve_details{hostname=~\"$hostname\",cve=~\"$nginx_cve\",base_score=~\"$base_score\",exploitability_score=~\"$exploitability_score\",severity=~\"$severity\"})",
     "legendFormat": "Expl. Score {{exploitability_score}}"
    }
   ]
  }
 ]
}